global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Mapster;
global using Microsoft.AspNetCore.Authorization;
global using Survay_Basket.API.Contracts.Authentication;
global using Survay_Basket.API.Contracts.Polls;
global using Survay_Basket.API.Abstractions;
global using Survay_Basket.API.Presistence;
global using Survay_Basket.API.Services;
global using Survay_Basket.API.Entities;
global using Survay_Basket.API;
global using Survay_Basket.API.Extensions;
global using Survay_Basket.API.Errors;
global using Microsoft.AspNetCore.Identity;
global using Survay_Basket.API.Authentication;
global using Survay_Basket.API.Authentication.Filters;
global using Survay_Basket.API.Abstractions.Consts;

